services:
  mysql:
    image: mysql:8.0
    container_name: quiz_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: myquiz
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - quiz_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: myquiz
      DB_USERNAME: quiz_user
      DB_PASSWORD: quiz_password
    networks:
      - quiz_network

  nginx:
    image: nginx:alpine
    container_name: quiz_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - quiz_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - quiz_network

volumes:
  mysql_data:

networks:
  quiz_network:
    driver: bridge